# Makes everything bigger
MULTIPLIER = 2

# Swerve Speed
MODULE_FPS = 12
MODULE_IPS = MODULE_FPS * 12
SPEED_PERCENTAGE = .5

# Robot Dimensions
WIDTH = 26 * MULTIPLIER
HEIGHT = 26 * MULTIPLIER

# Screen Size
# Every pixel is one inch
WINDOW_X_RAW = 663
WINDOW_Y_RAW = 338

WINDOW_X = WINDOW_X_RAW * MULTIPLIER
WINDOW_Y = WINDOW_Y_RAW * MULTIPLIER


